#yml语法可在百度上搜索
#server:
#  port: 8091
#spring:
#  profiles:
#    active: prod

#---
#server:
#  port: 8092
#spring:
#  profiles: dev

#--- 
#server:
#  port: 8093
#spring:
#  profiles: prod
    
#和实体类映射
#person:
#  name1: zhangsan
#  age: 10
#  isTeen: true
#  id:
#    idenNo: 1302
#    address: Beijing
#  #yml表示数组的方式
##  hobbies:
##    - Java
##    - Python
#  hobbies: [Java,Python]
#  #yml表示map的方式
##  testMap:
##    key1: value1
##    key2: value2
#  testMap: {key1: value1,key2: value2}
#  date: 2020-01-01
#  timestamp: 2020-02-02 00:00:00